name: Deploy via Remote ssh

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        # script: "cd /var/www/hmt &&  echo ${{ secrets.PK }}  || sudo ./server_deploy.sh"
        script: "cd /var/www/hmt &&  echo ${{ secrets.PK }}  || sudo ./server_deploy.sh"
